apiVersion: v1
kind: Secret
metadata:
  name: spring-secret
  namespace: devops
type: Opaque
data:
  spring.datasource.username: cm9vdA==      # base64 de "root"
  spring.datasource.password: cm9vdDEyMw==  # base64 de "root123"

